db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: node index.js
  volumes:
    - .:/geolocation
    - /geolocation/node_modules
  ports:
    - "9000:9000"
  links:
    - db
  environment:
    PORT: 9000 